# syntax=docker/dockerfile:1

FROM golang:1.19-alpine

WORKDIR /app

COPY . ./
RUN go mod download

RUN go build -o /unusual-database-program ./cmd/unusual-database-program

ENTRYPOINT [ "/unusual-database-program" ]
CMD [ "-host=fly-global-services" ]
