app = "winter-cloud-2400"

[[services]]
  internal_port = 5000
  protocol = "udp"

  [[services.ports]]
    port = "5000"

[[services]]
  internal_port = 5000
  protocol = "tcp"

  [[services.ports]]
    port = "5000"

  [services.concurrency]
    type = "connections"
    hard_limit = 200
    soft_limit = 150